---
description: Create, test, and delete a Signadot sandbox
inputs:
  action:
    default: create
    description: Signadot action to perform
    required: true
  response_file:
    default: .signadot/response.yml
    description: The response file to store created sandbox details; defaults to .signadot/response.yml
    required: true
  sha:
    description: The commit SHA of the image build to be deployed
    required: true
  signadot_api_key:
    default: ${{ secrets.SIGNADOT_API_KEY }}
    description: The Signadot API Key to use from https://app.signadot.com/settings/apikeys; defaults to secrets.SIGNADOT_API_KEY
    required: true
  signadot_org:
    description: The Signadot Organization Name to use from https://app.signadot.com/settings/global
    required: true
  template_file:
    default: .signadot/template.yml
    description: The template file to use for the sandbox; defaults to .signadot/template.yaml
    required: true
name: Signadot Sandbox
outputs:
  time:
    description: The time we greeted you
runs:
  args:
    - ${{ inputs.who-to-greet }}
  image: Dockerfile
  using: docker